"""
Django settings for omega_god project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(f+exv(dg!z^378-yka6=!gs#*97ncvgug0*o+$mn(@@!6$28w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'omega',
    'oapp',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'omega_god.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'omega_god.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ['GOD_DB_NAME'],
        'USER': os.environ['GOD_DB_USER'],
        'PASSWORD': os.environ['GOD_DB_PASSWORD'],
        'HOST': os.environ['GOD_DB_HOST'],
        'PORT': os.environ['GOD_DB_PORT'],
        },

    'omega': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ['OMEGA_DB_NAME'],
        'USER': os.environ['OMEGA_DB_USER'],
        'PASSWORD': os.environ['OMEGA_DB_PASSWORD'],
        'HOST': os.environ['OMEGA_DB_HOST'],
        'PORT': os.environ['OMEGA_DB_PORT'],
    },

    'oapp': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ['OAPP_DB_NAME'],
        'USER': os.environ['OAPP_DB_USER'],
        'PASSWORD': os.environ['OAPP_DB_PASSWORD'],
        'HOST': os.environ['OAPP_DB_HOST'],
        'PORT': os.environ['OAPP_DB_PORT'],
    },
}

DATABASE_ROUTERS = ['dbrouter.OmegaRouter', 'dbrouter.OappRouter']

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
